version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ychile_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --skip-ssl
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ychile
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
