import Head from "next/head";
import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from 'react-redux';
import Footer from "../footer/Footer";
import Header from "../header/Header";
import Modal from "../Modal/Modal";
import LoginComponent from "../Login/Login";
import SignupComponent from "../SignUp/SignUp";
import { AppDispatch, RootState } from '@/store/store';
import { initializeAuthFromCookies, logoutUser } from '@/store/auth/thunk';
import { AuthService } from "@/services/auth.service";
export const metadata = {
  title: "YCH",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export const MainLayout = ({ children }: Props) => {
  const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
  const [isSignupModalOpen, setIsSignupModalOpen] = useState(false);
  
  const dispatch = useDispatch<AppDispatch>();
  const user = useSelector((state: RootState) => state.auth.user);
  const isAuthenticated = useSelector((state: RootState) => state.auth.isAuthenticated);

  // Inicializar desde cookies al cargar
  useEffect(() => {
    dispatch(initializeAuthFromCookies());
  }, [dispatch]);

  const handleLogin = () => {
    setIsLoginModalOpen(true);
  }; 

  const handleLoginSuccess = (userData: any) => {
    setIsLoginModalOpen(false);
    // El store ya se actualiza automáticamente
  };

  const handleLogout = async () => {
    try {
      await dispatch(logoutUser());
    } catch (error) {
      console.error('Logout error:', error);
    }
  };

  const handleRegister = () => {
    setIsSignupModalOpen(true);
  };

  const handleSignupSuccess = (userData: any) => {
    setIsSignupModalOpen(false);
    // El store ya se actualiza automáticamente
  };

  const closeLoginModal = () => {
    setIsLoginModalOpen(false);
  };

  const closeSignupModal = () => {
    setIsSignupModalOpen(false);
  };

  return (
    <React.Fragment>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.title} />
        <link rel="icon" href="/assets/images/Logo.svg" />
      </Head>
      <div className="h-screen flex flex-col justify-between items-center">
        <Header 
          isLoggedIn={isAuthenticated}
          onLogin={handleLogin}
          onRegister={handleRegister}
          onLogout={handleLogout}
          userAvatar={user?.userImage || undefined}
          userName={user?.username}
        />
        <main className="py-5 p-5 bg-[#030711] w-full flex-1 overflow-auto">{children}</main>
        <Footer />
        
        {/* Login Modal */}
        <Modal isOpen={isLoginModalOpen} onClose={closeLoginModal}>
          <LoginComponent 
            onLoginSuccess={handleLoginSuccess}
            onClose={closeLoginModal}
          />
        </Modal>

        {/* Signup Modal */}
        <Modal isOpen={isSignupModalOpen} onClose={closeSignupModal}>
          <SignupComponent 
            onSignupSuccess={handleSignupSuccess}
            onClose={closeSignupModal}
          />
        </Modal>
      </div>
    </React.Fragment>
  );
};
