import Head from "next/head";
import React, { useState, useEffect } from "react";
import Footer from "../footer/Footer";
import Header from "../header/Header";
import Modal from "../Modal/Modal";
import LoginComponent from "../Login/Login";
import SignupComponent from "../SignUp/SignUp";
import { AuthService } from "@/services/auth.service";
export const metadata = {
  title: "YCH",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export const MainLayout = ({ children }: Props) => {
  const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
  const [isSignupModalOpen, setIsSignupModalOpen] = useState(false);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [user, setUser] = useState(null);
  
  const authService = new AuthService();

  // Verificar autenticación al cargar
  useEffect(() => {
    const token = authService.getToken();
    const userData = authService.getUser();
    
    if (token && userData) {
      setIsLoggedIn(true);
      setUser(userData);
    }
  }, []);

  const handleLogin = () => {
    setIsLoginModalOpen(true);
  };

  const handleLoginSuccess = (userData: any) => {
    setIsLoggedIn(true);
    setUser(userData);
    setIsLoginModalOpen(false);
  };

  const handleLogout = () => {
    authService.logout();
    setIsLoggedIn(false);
    setUser(null);
  };

  const handleRegister = () => {
    setIsSignupModalOpen(true);
  };

  const handleSignupSuccess = (userData: any) => {
    setIsLoggedIn(true);
    setUser(userData);
    setIsSignupModalOpen(false);
  };

  const closeLoginModal = () => {
    setIsLoginModalOpen(false);
  };

  const closeSignupModal = () => {
    setIsSignupModalOpen(false);
  };

  return (
    <React.Fragment>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.title} />
        <link rel="icon" href="/assets/images/Logo.svg" />
      </Head>
      <div className="h-screen flex flex-col justify-between items-center">
        <Header 
          isLoggedIn={isLoggedIn}
          onLogin={handleLogin}
          onRegister={handleRegister}
          userAvatar={user?.avatar}
          userName={user?.name}
        />
        <main className="py-5 p-5 bg-[#030711] w-full flex-1 overflow-auto">{children}</main>
        <Footer />
        
        {/* Login Modal */}
        <Modal isOpen={isLoginModalOpen} onClose={closeLoginModal}>
          <LoginComponent 
            onLoginSuccess={handleLoginSuccess}
            onClose={closeLoginModal}
          />
        </Modal>

        {/* Signup Modal */}
        <Modal isOpen={isSignupModalOpen} onClose={closeSignupModal}>
          <SignupComponent 
            onSignupSuccess={handleSignupSuccess}
            onClose={closeSignupModal}
          />
        </Modal>
      </div>
    </React.Fragment>
  );
};
