import Head from "next/head";
import React from "react";
import Footer from "../footer/Footer";
import Header from "../header/Header";
export const metadata = {
  title: "YCH",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export const MainLayout = ({ children }: Props) => {
  return (
    <React.Fragment>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.title} />
        <link rel="icon" href="/assets/images/Logo.svg" />
      </Head>
      <div className="h-screen flex flex-col justify-between items-center">
        <Header />
        <main className="py-5 p-5 bg-[#030711] w-full flex-1 overflow-auto">{children}</main>        <Footer />
      </div>
    </React.Fragment>
  );
};
